---
- name: Habilitar IPv6 y configurar Loopback1
  hosts: csr
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Habilitar IPv6 globalmente
      ios_config:
        lines:
          - ipv6 unicast-routing

    - name: Configurar IPv6 en Loopback1
      ios_config:
        parents: interface Loopback44
        lines:
          - ipv6 address 3001:ABCD:ABCD:4::4/128
          - ipv6 address FE80::1 link-local


